name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout
    - uses: actions/setup-node
#     - uses: ./action-a
    - run: npm --version
    - run: node --version
#       env:
#         MY_NAME: "Mona"
